# Generated by Django 3.2.3 on 2021-05-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20210528_0919'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
