# Generated by Django 3.2.3 on 2021-05-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_alter_bookinfo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='heroinfo',
            table='heroinfo',
        ),
    ]
