# Generated by Django 3.2.3 on 2021-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_areainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_pic', models.ImageField(upload_to='booktest')),
            ],
        ),
        migrations.AlterField(
            model_name='areainfo',
            name='atitle',
            field=models.CharField(max_length=20, verbose_name='标题'),
        ),
    ]
